channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.0
name: mlflow-env
